config/routes.rb
Rails.application.routes.draw do
  root 'sections#index'
  resources :lessons
  resources :sections

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  validates_presence_of :title, :sort_order, :content
  belongs_to :section

  def next
    lessons = Lesson.all.order(sort_order: :asc)
    @next_lesson = lessons.select{ |lesson|
      lesson.sort_order > sort_order
    }[0]
  end

  def prev
    lessons = Lesson.all.order(sort_order: :asc)
    @prev_lesson = lessons.select{ |lesson|
      lesson.sort_order < sort_order
    }[-1]
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  validates_presence_of :title

  has_many :lessons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def index
    @lessons = Lesson.all.order(sort_order: :asc)
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(lesson_params)
    if params[:lesson][:add_section] != nil && params[:lesson][:add_section] != ""
      section = Section.create(title: params[:lesson][:add_section])
      @lesson.section_id = section.id
    end
    if @lesson.save
      redirect_to @lesson
    else
      render :new
    end
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])
    if @lesson.update(lesson_params)
      redirect_to @lesson
    else
      render :edit
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    redirect_to lessons_path
  end

  private

  def lesson_params
    params.require(:lesson).permit(:title, :content, :sort_order, :section_id)
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  def index
    @sections = Section.all
  end

  def show
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      redirect_to @section
    else
      render :new
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    if @section.update(section_params)
      redirect_to @section
    else
      render :edit
    end
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    redirect_to sections_path
  end

  private

  def section_params
    params.require(:section).permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %>Learn How To Program</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lessons/_form.html.erb
<%= render 'layouts/errors', object: @lesson %>

<%= form_for @lesson do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.label :sort_order %>
  <%= f.text_field :sort_order %>

  <%= f.label :section %>
  <%= f.collection_select :section_id, Section.all, :id, :title %>

  <label for="add_section">Add A Section</label>
  <input type="text" name="lesson[add_section]" id="add_section">

  <%= f.submit %>
<% end %>

app/views/lessons/edit.html.erb
<% content_for :title, "Edit #{@lesson.title} - "%>

<h1>Edit Lesson</h1>

<%= render 'form' %>

app/views/lessons/index.html.erb
<h1>Table of Contents</h1>

<ul>
  <% @lessons.each do |lesson| %>
    <li><%= link_to lesson.title, lesson %></li>
  <% end %>
</ul>

<%= link_to 'new', new_lesson_path %>

app/views/lessons/new.html.erb
<% content_for :title, "New Lesson - "%>

<h1>New Lesson</h1>

<%= render 'form' %>

app/views/lessons/show.html.erb
<% content_for(:title, "#{@lesson.title} - ") %>

<h1><%= @lesson.title %></h1>
<p><%= link_to 'edit', edit_lesson_path(@lesson) %> | <%= link_to 'delete', lesson_path(@lesson), data: {confirm: "Are you sure?", method: "delete"} %></p>
<p><%= @lesson.content %></p>

<p>
  <% if @lesson.prev %>
    <%= link_to "Previous Lesson", @lesson.prev%> |
  <% end %>
  <%= link_to "Home", lessons_path %>
  <% if @lesson.next %>
    | <%= link_to "Next Lesson", @lesson.next%>
  <% end %>
</p>